### ISSUE TITLE
No grad2 in current context C# 2S

### ISSUE THREAD

**Issue by s19818** [KdotJPG/OpenSimplex2#13]
Grad3 is there but grad2 array is missing.

**Comment by hamarb123** [comment]
I copied out of the java one, it is the same.

**Comment by KdotJPG** [comment]
Huh. Not sure how I missed this. I must have saved the file on the wrong undo step while trying something after verifying it worked. Either way, good catch! The latest commit should resolve it.

**Comment by s19818** [comment]
Perfect!
