### ISSUE TITLE
Why the use of both float and double in the OpenSimplex2S.java file?

### ISSUE THREAD

**Issue by brett-carsales** [KdotJPG/OpenSimplex2#16]
I am porting this file to Swift to use in an art project and was wondering why the use of floats in this version? A lot of functions take double parameters but return a float. Is this just because the the output of the noise is generally mapped to something like an RGB value or angle or height map etc and accuracy there tends not to be that important ?

**Comment by KdotJPG** [comment]
Correct, the doubles are only needed to support large input coordinate ranges. Floats have plenty of precision for just about anything the output would be used for.

**Comment by brett-carsales** [comment]
Makes sense, thanks for the quick reply. Have ported this to Swift and am currently testing it.
