### ISSUE TITLE
Scaling factors

### ISSUE THREAD

**Issue by mfiano** [KdotJPG/OpenSimplex2#18]
Could you enlighten us on the method you use to calculate the scaling factors of your noise algorithms? Some example code would be much appreciated. Thank you.

**Comment by KdotJPG** [comment]
Hmm, do you mean the output scaling factors that get applied to the gradient tables to make the range -1 to 1? I wrote an article on it here: https://noiseposti.ng/posts/2021-03-22-Normalizing-Gradient-Noise.html

**Comment by mfiano** [comment]
Thanks!
